# Generated by Django 4.2.5 on 2023-09-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('token_used', models.IntegerField()),
                ('token_prompt', models.IntegerField()),
                ('token_completion', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('desc', models.TextField()),
                ('status', models.SmallIntegerField()),
            ],
        ),
    ]
